# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50ea0ba2c0f97b5d3487517353aa0649919163856191bf5c517f741a0c5f91909f17693ef300f848e05eb2c5e802d0e4dd54dec9072a6098865ac608385acd68

test:
  secret_key_base: 7e626716d05f74ab16e9e7e12fd553ae579f5ef9cbfa2765c64f9702cdf9f974461632d2e6e5bdba056fd8d6c5b1f8891fb52bdef77c5878aacb93ed7cfb7484

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
